### PR TITLE
Cloud formation support

### LINKED ISSUE #20: dataSources / tableName as Ref not processed / InvalidParameterType: Expected params.TableName to be a string
Using a "Ref: " for tableName is not supported

```
dataSources:
      - type: AMAZON_DYNAMODB
        name: UsersTableDS
        description: 'Users table'
        config:
          #tableName: conda-test-appsync-ah-users
          tableName: { Ref: UsersTable }
          serviceRoleArn: { Fn::GetAtt: [ DynamoDBRole, Arn ] }
```

### Error:
```
start Resolve: Query.allUsers [allUsers]
ℹ info Rendered Request:

  { version: '2017-02-28',
    operation: 'Scan',
    limit: 2,
    nextToken: null }
ℹ info Dispatch to source
  { name: 'UsersTableDS', type: 'AMAZON_DYNAMODB' }
✖ error Query.allUsers failed
✖ error InvalidParameterType: Expected params.TableName to be a string
  at ParamValidator.fail (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/param_validator.js:50:37)
  at ParamValidator.validateType (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/param_validator.js:222:10)
  at ParamValidator.validateString (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/param_validator.js:154:32)
  at ParamValidator.validateScalar (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/param_validator.js:130:21)
  at ParamValidator.validateMember (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/param_validator.js:94:21)
  at ParamValidator.validateStructure (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/param_validator.js:75:14)
  at ParamValidator.validateMember (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/param_validator.js:88:21)
  at ParamValidator.validate (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/param_validator.js:34:10)
  at Request.VALIDATE_PARAMETERS (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/event_listeners.js:125:42)
  at Request.callListeners (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/sequential_executor.js:109:20)
  at callNextListener (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/sequential_executor.js:99:12)
  at /Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/event_listeners.js:85:9
  at finish (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/config.js:322:7)
  at /Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/config.js:340:9
  at Credentials.get (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/credentials.js:126:7)
  at getAsyncCredentials (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/config.js:334:24)
  at Config.getCredentials (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/config.js:354:9)
  at Request.VALIDATE_CREDENTIALS (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/event_listeners.js:80:26)
  at Request.callListeners (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/sequential_executor.js:105:18)
  at Request.emit (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/sequential_executor.js:81:10)
  at Request.emit (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/request.js:683:14)
  at Request.transition (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/request.js:22:10)
  at AcceptorStateMachine.runTo (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/state_machine.js:14:12)
  at Request.runTo (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/request.js:403:15)
  at /Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/request.js:792:12
  at new Promise (<anonymous>)
  at Request.promise (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/aws-sdk/lib/request.js:778:12)
  at scan (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/@conduitvc/appsync-emulator-serverless/dynamodbSource.js:213:29)
  at resolve (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/@conduitvc/appsync-emulator-serverless/dynamodbSource.js:387:14)
  at dispatchRequestToSource (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/@conduitvc/appsync-emulator-serverless/schema.js:156:14)
  at /Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/@conduitvc/appsync-emulator-serverless/schema.js:202:33
  at resolveFieldValueOrError (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/graphql/execution/execute.js:531:18)
  at resolveField (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/graphql/execution/execute.js:495:16)
  at /Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/graphql/execution/execute.js:364:18
  at Array.reduce (<anonymous>)
  at executeFields (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/graphql/execution/execute.js:361:42)
  at executeOperation (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/graphql/execution/execute.js:289:122)
  at executeImpl (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/graphql/execution/execute.js:154:14)
  at execute (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/graphql/execution/execute.js:131:229)
  at executeGQL (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/@conduitvc/appsync-emulator-serverless/serverCore.js:235:24)
  at /Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/@conduitvc/appsync-emulator-serverless/serverCore.js:282:15
  at app.post (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/@conduitvc/appsync-emulator-serverless/serverCore.js:328:13)
  at Layer.handle [as handle_request] (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/express/lib/router/layer.js:95:5)
  at next (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/express/lib/router/route.js:137:13)
  at Route.dispatch (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/express/lib/router/route.js:112:3)
  at Layer.handle [as handle_request] (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/express/lib/router/layer.js:95:5)
  at /Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/express/lib/router/index.js:281:22
  at Function.process_params (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/express/lib/router/index.js:335:12)
  at next (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/express/lib/router/index.js:275:10)
  at cors (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/cors/lib/index.js:188:7)
  at /Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/cors/lib/index.js:224:17
  at originCallback (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/cors/lib/index.js:214:15)
  at /Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/cors/lib/index.js:219:13
  at optionsCallback (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/cors/lib/index.js:199:9)
  at corsMiddleware (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/cors/lib/index.js:204:7)
  at Layer.handle [as handle_request] (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/express/lib/router/index.js:317:13)
  at /Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/express/lib/router/index.js:284:7
  at Function.process_params (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/express/lib/router/index.js:335:12)
  at next (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/express/lib/router/index.js:275:10)
  at /Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/body-parser/lib/read.js:130:5
  at invokeCallback (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/raw-body/index.js:224:16)
  at done (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/raw-body/index.js:213:7)
  at IncomingMessage.onEnd (/Users/ah/SVN-Checkouts/CONDA/conda-registration-login/server/node_modules/raw-body/index.js:273:7)
  at IncomingMessage.emit (events.js:180:13)
  at IncomingMessage.emit (domain.js:422:20)
  at endReadableNT (_stream_readable.js:1106:12)
  at process._tickCallback (internal/process/next_tick.js:178:19)
```

There is no problem if `{ Ref: UsersTable }` is replaced with a string - e.g. "appnam-users-table"

### PR DESCRIPTION
**Pull request by lightsofapollo**
Should fix #20

I took the approach of creating a standalone module that we can use to add further support for CF. I imagine `Ref` being the most useful (so that is the first thing added in this PR) but others (Join?) could be useful as well.

### TODO

 - [ ] Test nodejs environment variables for dynamodb (can we axe this?)
 - [ ] Update readme with new features

### CODE REVIEW

File: packages/appsync-emulator-serverless/cloudFormationProcessor.js [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+        )})`,
+      );
+  }
+}
+
+const cloudFormationHandlers = {
+  Ref: cfRef,
+};
+
+function processObject(object, ctx, objectPath = []) {
```
Comment (lightsofapollo) [inline packages/appsync-emulator-serverless/cloudFormationProcessor.js]: ## Object path

I took extra care to make this debuggable... One of the key features of the emulator should be better iteration loop which means better error messages. This will allow one to track down which line of their cloud formation function is on.

When something goes wrong you will get an error message like `... (custom.appSync.bla)`

File: packages/appsync-emulator-serverless/dynamodbSource.js [hunk 2]
```diff
@@ -381,8 +381,7 @@ const batchDeleteItem = async (db, dynamodbTables, { tables }) => {
   };
 };
 
-const resolve = async (dynamodb, defaultAlias, dynamodbTables, payload) => {
-  const table = dynamodbTables[defaultAlias];
```
Comment (lightsofapollo) [inline packages/appsync-emulator-serverless/dynamodbSource.js]: NOTE: This may not be obvious but is a large breaking change. We should encourage use of Ref going forward for aliases of tables. Today the only place where we need/use these alias values is in batch items which *must* always be referred to by name in the queries so we can't use any CF magic there to help.

File: packages/appsync-emulator-serverless/schemaTest.js [hunk 3]
```diff
@@ -21,21 +22,15 @@ const setupDocumentDB = async (serverlessConfig, appSyncConfig, dynamodb) => {
...
     );
 
-  const { dataSources = [] } = appSyncConfig;
-  const appSyncTables = dataSources.filter(
-    source => source.type === 'AMAZON_DYNAMODB',
-  );
-
   const list = await Promise.all(
-    appSyncTables.map(async ({ config: { tableName } }) => {
+    Object.values(resourceTables).map(async ({ Properties: props }) => {
```
Comment (lightsofapollo) [inline packages/appsync-emulator-serverless/schemaTest.js]: small but notable change... we now create *all* tables listed instead of just those used by appasync.

File: packages/appsync-emulator-serverless/cloudFormationProcessor.js [hunk 4]
```diff
@@ -0,0 +1,104 @@
...
+  if (Array.isArray(object)) {
+    return object.map((value, idx) =>
+      processObject(value, ctx, [...objectPath, idx]),
+    );
+  }
+
+  const entries = Object.entries(object);
+  return entries.reduce((sum, [key, value]) => {
+    const newObjectPath = [...objectPath, key];
+    if (entries.length === 1 && cloudFormationHandlers[key]) {
```
Comment (cbaron) [inline packages/appsync-emulator-serverless/cloudFormationProcessor.js]: would this be easier to read if we pull this if block out of the reduce?

File: packages/appsync-emulator-serverless/cloudFormationProcessor.js [hunk 5]
```diff
@@ -0,0 +1,104 @@
...
+    }
+    return {
+      ...sum,
+      [key]: processObject(value, ctx, newObjectPath),
+    };
+  }, {});
+}
+
+function cloudFormationProcessor(input, { dynamodbTables }) {
+  const config = { ...input };
```
Comment (cbaron) [inline packages/appsync-emulator-serverless/cloudFormationProcessor.js]: one could also:

```
const { serverless, ...config } = input
```

if you wanted to spare the `delete` command on L100

File: packages/appsync-emulator-serverless/dynamodbSource.js (hunk 2 above)
Comment (cbaron) [reply packages/appsync-emulator-serverless/dynamodbSource.js]: Do we need to worry about our [hack](https://github.com/ConduitVC/aws-utils/blob/66530e7decaf65b1a3a895f536418d0fe61a2a1b/packages/appsync-emulator-serverless/lambdaSource.js#L34) which includes dynamodb table name mappings when running a lambda method?

Comment (lightsofapollo) [reply packages/appsync-emulator-serverless/dynamodbSource.js]: Good question... I will test. I had assumed honestly the test suite would catch it.

**Comment by cbaron** [comment]
@lightsofapollo -- do you want me to pick this up?

**Comment by lightsofapollo** [comment]
@cbaron If you can that would be awesome.

**Comment by bboure** [comment]
@lightsofapollo @cbaron  I'd love to see that land. 
Let me know if I can help

**Comment by cbaron** [comment]
@bboure -- my apologies, but I haven't had time -- you're certainly welcome to push this along, I know many folks have asked for it.

**Comment by lightsofapollo** [comment]
@bboure I don't have time this week but neither of you have a moment to land this I will take a look next weekend (hold me to this :))

**Comment by lightsofapollo** [comment]
NOTE: This does contain a breaking change and IMO should justify a `v1.0` for communication purposes.

/cc @bboure @cbaron

File: packages/appsync-emulator-serverless/schemaTest.js [hunk 6]
```diff
@@ -21,21 +22,15 @@ const setupDocumentDB = async (serverlessConfig, appSyncConfig, dynamodb) => {
...
       const testName = uuid();
-      const resourceConfig = resourceTables[tableName];
       const tableConfig = {
-        ...resourceConfig.Properties,
+        ...props,
         TableName: testName,
       };
       await dynamodb.createTable(tableConfig).promise();
-      return { testName, tableName };
+      return { testName, tableName: props.TableName };
```
Comment (lightsofapollo) [inline packages/appsync-emulator-serverless/schemaTest.js]: this introduced a bug I believe.
